### ISSUE TITLE
Too many false positives

### ISSUE THREAD

**Issue by rtfpessoa** [wooorm/retext-spell#14]
Is there a way to disable errors for words it does not recognize?

For example when I am writing technical content, with peoples names I get hundreds of occurrences that I would have to add to my dictionary or ignore list. Is there a way to only check words that he has confidence or suggestions?

**Comment by wooorm** [comment]
@rtfpessoa See the [options described in the readme](https://github.com/retextjs/retext-spell#options): `personal` and `ignore` seem relevant.

**Comment by rtfpessoa** [comment]
Like I mentioned in my question:

>  I get hundreds of occurrences that I would have to add to my dictionary or ignore list

In each text I write I need to add more that 10 words to the dictionary. And I would just prefer to have only warning for words that `retext-spell` knows are wrong or at least has some confidence and not just all the words it does not know.

**Comment by wooorm** [comment]
@rtfpessoa That seems to be an issue with the dictionary you use.

> only warning for words that retext-spell knows are wrong or at least has some confidence and not just all the words it does not know.

How else do you propose spell checkers / dictionaries work? 🤔

**Comment by rtfpessoa** [comment]
@wooorm that is a very interesting questions. I actually have any idea how a spell checker works :smile: 

I am using `dictionary-en-us` but I have problems with words like:

```
changelog
dropdown
retext
viewlet
PHP
linter
CircleCI
Docker
Gitlab
GitHub
Bitbucket
integrations
Roadmap
Testrail
Jira
onboarding
offboarding
CRM
Bitwarden
AWS
Datadog
IntelliJ
MacDown
async
Authy
2FA
Doplicated
SBT
keybind
MacOS
VM
Route53
BigQuery
dataset
DataStudio
saml2aws
GMail
DevOps
GSuite
WebConsole
IAM
SSO
VPN
Iterm2
GrayLog
DNS
subtask
hotfix
TestRail
```

Any suggestions?

**Comment by wooorm** [comment]
Hmm, well, I don’t think other spell checkers accept these either (they all essentially have a big list of valid words). All these words are jargon or names of things, not “normal american english”. This is not a bug, it’s a feature. And if you don’t want to get warned by them, place them in a personal dictionary! 🤷‍♂️

**Comment by rtfpessoa** [comment]
Ok, thank you.
