### ISSUE TITLE
Multiple dictionaries

### ISSUE THREAD

**Issue by maxwondercorn** [wooorm/retext-spell#15]
Is it possible to allow more than one dictionary for retest-spell?  I have an open source project where I need to the use an English dictionary for general spell checking and a project specific one for the technical/unique words.

I need an affix file for the project specific, so I can't use the personal dictionary option. NSpell supports multiple dictionaries being passed.

**Comment by wooorm** [comment]
`dictionary` can be any function. It’s given a function (`cb(err, res)`), and you must call that function with `err` if loading fails, or `res` if successful, where `res` is either one dictionary or an array of dictionaries!
