### ISSUE TITLE
Not available via NPM :O(

### ISSUE THREAD

**Issue by s-a** [wooorm/retext-spell#2]

**Comment by wooorm** [comment]
Yup, it doesn’t work yet, nodehun is a bit broken and I couldn’t get it to pass.

I started work on an alternative Hunspell-compatible JavaScript implementation, but it’s a lot of work (reverse engineering, as the license of hunspell is not permissive) and I shelved it for now :( I cannot yet tell you when it’s going to work! :(

**Comment by s-a** [comment]
just found this which look promising. https://github.com/atom/node-spellchecker

**Comment by s-a** [comment]
as far as i can see we could write a simple retext plugin to adapt node-spellchecker module right?

**Comment by wooorm** [comment]
It doesn’t support dictionaries unfortunately, which I’d really like!

**Comment by s-a** [comment]
I see them here https://github.com/atom/node-spellchecker/tree/master/vendor/hunspell_dictionaries or what do you mean?

**Comment by wooorm** [comment]
Ah, [found it](https://github.com/atom/node-spellchecker/blob/531a9743f99e9c6f0e0123e0112f665a08184a18/lib/spellchecker.js#L73)!

However, from what I see, that function receives two arguments: a language tag (for example, `en_US`), and a directory name (e.g., `foo/bar`). Then, it loads files in that directory, with names of the language, and extensions of either `.aff` or `.dic`. Meaning, the list of dictionaries I published wont work: [`wooorm/dictionaries`](https://github.com/wooorm/dictionaries) :(

**Comment by wooorm** [comment]
Closing this for now, sozzzz. Somewhere in the future!
