### ISSUE TITLE
Ignore times in common formats (e.g. 2:41PM)

### ISSUE THREAD

**Issue by danielgolden** [wooorm/retext-spell#24]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.1.0

### Link to runnable example

https://peaceful-mclean-b30fef.netlify.app

### Steps to reproduce

1. Open the [runnable example](https://peaceful-mclean-b30fef.netlify.app).
2. In the text field, paste the following string: `Good morning, today is 2:41pm.`
3. In the right pane, you'll see that a warning is returned for the time of day.

## Expected behavior
**TL;DR**: I expect that the retext-spell plugin wouldn't return any warnings for times in common formats like `2:41pm`.

### Description
First, retext and unified as a whole is an _incredible project_. _Thank you_ for making and maintaining this.

I'm working on creating a JavaScript prose linter for anyone who writes copy in our UI. It's accessible via a browser or in a [Figma](http://figma.com) Plugin since it's primarily meant for product designers to use. [The prose linter](https://peaceful-mclean-b30fef.netlify.app) that I've created uses many existing retext plugins (like retext-spell) and several custom plugins for rules to help our teams adhere to our writing style guide. Since my company is a software monitoring tool, we often use times (e.g. 2:41pm) in our UI and it's very plausible that folks will attempt to use my plugin on text layers that contain times.

I'm taking advantage of the `ignoreDigits` option and it's working wonderfully! I was hoping to find another option that allows consumers of the project to control whether to ignore words that contain _any_ digits as opposed to _only_ digits (as the `ignoreDigits` option does).

### Affected runtime and version

node@14.15.5

### Affected package manager and version

npm@8.10.0

### Affected OS and version

macOS Monterey 12.2.1

### Build and bundle tools

webpack, Vite

**Comment by wooorm** [comment]
Good idea.
If you are interested in a PR, it could be solved here: https://github.com/retextjs/retext-spell/blob/0b85545e8efc1e50faefe6c9dd1a76163c9ad08b/index.js#L289.

**Comment by danielgolden** [comment]
Awesome. Thanks for the feedback! I'm definitely interested. 
I'll try to submit a PR for it this week.

**Comment by wooorm** [comment]
Released in [`5.3.0`](https://github.com/retextjs/retext-spell/releases/tag/5.3.0)!
