### ISSUE TITLE
v1.0.0 not flagging spelling errors

### ISSUE THREAD

**Issue by localjo** [wooorm/retext-spell#9]
I tried plugging v1.0.0 of `retext-spell` into [`quality-docs`](https://github.com/sparkartgroup/quality-docs), but it wasn't flagging any spelling errors. I thought maybe the spelling errors were being swallowed be some other filter I had in my code, so I stripped everything out, and eventually tried the usage example from the README;

```
var retext = require('retext');
var spell = require('retext-spell');
var dictionary = require('dictionary-en-gb');
var report = require('vfile-reporter');

retext()
  .use(spell, dictionary)
  .process('Some useles mispelt documeant.', function (err, file) {
    console.error(report(err || file));
  });
```

When I save that as `index.js` and run it with `node index.js`, I get;

```
no issues found
```

So I think version 1.0.0 is not flagging spelling errors at all.

**Comment by wooorm** [comment]
Argh, sorry about that. What version of retext are you on?

**Comment by wooorm** [comment]
Oh I’m just seeing that I haven't updated this plugin yet, for the latest retext, sorry about that.
I’ll have a fix in an hour or so! (if that’s the reason your case doesn't work)

**Comment by localjo** [comment]
Was using `retext@3.0.0`. I didn't think about that. I'll try with `retext@5.0.0`.

**Comment by localjo** [comment]
With `retext@5.0.0` I get this error;

```
/path/quality-docs/node_modules/retext-spell/index.js:28
    throw new Error('Expected `Object`, got `' + load + '`');
    ^

Error: Expected `Object`, got `undefined`
    at Function.spell (/path/quality-docs/node_modules/retext-spell/index.js:28:11)
```

**Comment by wooorm** [comment]
Right, that error tells me it’s cause I haven’t upgraded yet. Sorry about that!

**Comment by wooorm** [comment]
This should do the trick! (2.0.0 will be released in a minute)
